site_name: Reneo
site_url: "https://github.com/Vini2/reneo"
site_author: "Vijini Mallawaarachchi"
repo_url: "https://github.com/Vini2/reneo"
repo_name: 'GitHub'
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - bash
        - shell
        - text
nav:
    - Home:
      - Introduction: index.md